import Head from "next/head";
import { useContext } from "react";

// Importing StyleSheet
import styles from "../styles/Home.module.css";

// Importing Context
import Content from "./Operation/Content";
import { NUSDContext } from "../context/Context";

// Connect Page
import ConnectWallet from "./Operation/ConnectWallet";


export default function Home() {
  
  // Destructuring Context
  const context = useContext(NUSDContext);
  const { ContextAddress, ContextSigner } = context;
  
  return (
    <>
    {/* Website Title and Icon */}
      <Head>
        <title>UNREAL finance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav.png" />
      </Head>

      {/* Main Stuff */}
      <main className={styles.main}>
        {/* Only For Some design */}
        <div className={styles.circle1}></div>
        <div className={styles.circle2}></div>

        {/* Checking if Account Address is not there than Connect  Wallet Page Open */}
        <div className={styles.container}>
          {ContextAddress == undefined ? <ConnectWallet /> : <Content />}
        </div>
      </main>
    </>
  );
}
